image:
  - Visual Studio 2022

stack: python 3

environment:
  PY_DIR: C:\Python39-x64

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
  - cmd: SET PATH=%PATH%;C:\Program Files (x86)\Inno Setup 6
  - cmd: pip install -r requirements.txt
  - cmd: pip freeze

build_script:
  - cmd: cd external
  - cmd: curl -L -o ffmpg.7z https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-essentials.7z
  - cmd: 7z e ffmpg.7z  *.exe -r
  - cmd: curl -L -o youtube-dl.exe https://youtube-dl.org/downloads/latest/youtube-dl.exe
  - cmd: copy C:\Windows\SysWOW64\msvcr100.dll .
  - cmd: cd ..
  - cmd: python create_version.py
  - cmd: pyside6-rcc.exe .\resources.qrc -o resources.py
  - cmd: python create_inno_installer.py
  - cmd: pyinstaller.exe -F -w -i ficus.ico ficus.py
  - cmd: copy .\dist\ficus.exe .
  - cmd: iscc installer.iss
  - cmd: del ficus.exe

artifacts:
  - path: '*.exe'
    name: myartifact

deploy:
  tag: $(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: v$(appveyor_build_version)
  provider: GitHub
          # Αυτό είναι το νέο token auth_token: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
    secure: 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

  artifact: myartifact
  draft: false
  prerelease: false
  on:
    branch: master # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
