image:
  - Visual Studio 2022

stack: python 3

environment:
  PY_DIR: C:\Python39-x64

platform:
  - x64

branches:
  only:
    - master

skip_tags: true

install:
  - cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%
  - cmd: pip install -r requirements.txt
  - cmd: pip freeze

build_script:
  # - cmd: externals.ps1
  - cmd: python create_version.py
  - cmd: pyside6-rcc.exe .\resources.qrc -o resources.py
  - cmd: python create_nsi_installer.py
  - cmd: pyinstaller.exe -F -w -i ficus.ico ficus.py
  - cmd: copy .\dist\ficus.exe .
  # - cmd: makensis.exe installer.nsi

artifacts:
  - path: '*.exe'
    name: myartifact

deploy:
  tag: $(appveyor_build_version)
  release: v$(appveyor_build_version)
  description: v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: hvqOsOJoBzZ0iIiQN3CvgB/mnJOwfr7lHfxni9DcgwGzWqCuj82bOzNE6iylOKsk

  artifact: myartifact
  draft: false
  prerelease: false
  on:
    branch: master # release from master branch only
#    APPVEYOR_REPO_TAG: true        # deploy on tag push only
